require soap/encodingstyle/handler
#@include(aspDotNetHandler/EncodingStyle__ASPDotNetHandler)
#@include(aspDotNetHandler/EncodingStyle__ASPDotNetHandler__SOAPTemporalObject)
#@include(aspDotNetHandler/EncodingStyle__ASPDotNetHandler__SOAPUnknown)
