require soap/encodingstyle/handler
#@include(literalHandler/EncodingStyle__LiteralHandler)
#@include(literalHandler/EncodingStyle__LiteralHandler__SOAPTemporalObject)
#@include(literalHandler/EncodingStyle__LiteralHandler__SOAPUnknown)
